import fs from 'node:fs';
import path from 'node:path';
import { EnvironmentAssetDef } from '../../src/game/environment/EnvironmentAsset';

const ROOT_DIR = process.cwd();

const manifestFiles = [
  'art/manifests/mansion-architecture.json',
  'art/manifests/ddwd_env_02.json',
  'art/manifests/ddwd_env_03.json',
  'art/manifests/ddwd_env_04.json',
  'art/manifests/ddwd_env_05.json',
  'art/manifests/ddwd_env_06.json',
  'art/manifests/ddwd_env_07.json',
  'art/manifests/ddwd_env_08.json',
  'art/manifests/ddwd_env_11.json',
];

interface RawManifestAsset {
  id: string;
  category: string;
  textureKey?: string;
  sourceRect?: { x: number; y: number; width: number; height: number };
  nativeWidth?: number;
  nativeHeight?: number;
  anchorPreset?: EnvironmentAssetDef['anchorPreset'];
  depthClass?: EnvironmentAssetDef['depthClass'];
  physicalClass?: EnvironmentAssetDef['physicalClass'];
  collisionProfile?: EnvironmentAssetDef['collisionProfile'];
  mirrorSafe?: boolean;
  repeatable?: boolean;
  lightSockets?: EnvironmentAssetDef['lightSockets'];
  surfaces?: EnvironmentAssetDef['surfaces'];
  windowMasks?: EnvironmentAssetDef['windowMasks'];
  notes?: string;
}

interface RawManifest {
  packId?: string;
  assets: RawManifestAsset[];
}

export function buildCompiledCatalog(): void {
  const catalog: Record<string, EnvironmentAssetDef> = {};

  for (const rel of manifestFiles) {
    const full = path.join(ROOT_DIR, rel);
    if (!fs.existsSync(full)) continue;
    const manifest: RawManifest = JSON.parse(fs.readFileSync(full, 'utf-8'));
    const packId = manifest.packId || 'mansion_architecture';

    for (const asset of manifest.assets) {
      const isAtlas = packId.startsWith('ddwd_env_');
      const textureKey = isAtlas ? packId : (asset.textureKey || asset.id);
      const frame = isAtlas ? asset.id : undefined;

      catalog[asset.id] = {
        id: asset.id,
        category: asset.category,
        textureKey,
        frame,
        packId,
        nativeWidth: asset.sourceRect ? asset.sourceRect.width : (asset.nativeWidth || 32),
        nativeHeight: asset.sourceRect ? asset.sourceRect.height : (asset.nativeHeight || 32),
        anchorPreset: asset.anchorPreset || 'bottom-center',
        depthClass: asset.depthClass || 'dynamic-solid',
        physicalClass: asset.physicalClass || 'none',
        collisionProfile: asset.collisionProfile || 'none',
        mirrorSafe: asset.mirrorSafe !== false,
        repeatable: !!asset.repeatable,
        lightSockets: asset.lightSockets,
        surfaces: asset.surfaces,
        windowMasks: asset.windowMasks,
        notes: asset.notes || '',
      };
    }
  }

  const outTs = `// AUTO-GENERATED BY tools/assets/build-compiled-catalog.ts - DO NOT EDIT MANUALLY
import { EnvironmentAssetDef } from './EnvironmentAsset';
import { CollisionProfile, getCollisionProfile } from './CollisionProfile';

export const ENVIRONMENT_ASSETS: Record<string, EnvironmentAssetDef> = ${JSON.stringify(catalog, null, 2)};

export class EnvironmentAssetCatalog {
  private static assets: Map<string, EnvironmentAssetDef> = new Map(
    Object.entries(ENVIRONMENT_ASSETS)
  );

  public static getAsset(id: string): EnvironmentAssetDef | undefined {
    return this.assets.get(id);
  }

  public static requireAsset(id: string): EnvironmentAssetDef {
    const asset = this.assets.get(id);
    if (!asset) {
      throw new Error(\`Environment asset not found in catalog: \${id}\`);
    }
    return asset;
  }

  public static hasAsset(id: string): boolean {
    return this.assets.has(id);
  }

  public static getAllAssets(): EnvironmentAssetDef[] {
    return Array.from(this.assets.values());
  }

  public static getAssetsByCategory(category: string): EnvironmentAssetDef[] {
    return this.getAllAssets().filter((a) => a.category === category);
  }

  public static getAssetsByPack(packId: string): EnvironmentAssetDef[] {
    return this.getAllAssets().filter((a) => a.packId === packId);
  }

  public static getCollisionProfileForAsset(id: string): CollisionProfile {
    const asset = this.assets.get(id);
    if (!asset) return getCollisionProfile('none');
    return getCollisionProfile(asset.collisionProfile);
  }
}
`;

  fs.writeFileSync(path.join(ROOT_DIR, 'src/game/environment/EnvironmentAssetCatalog.ts'), outTs);
  console.log(`Generated EnvironmentAssetCatalog.ts with ${Object.keys(catalog).length} assets!`);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  buildCompiledCatalog();
}
