import Phaser from 'phaser';

export type ArchitectureCategory =
  | 'floors'
  | 'carpets'
  | 'walls'
  | 'trims'
  | 'columns_arches'
  | 'stairs_balustrade'
  | 'ornaments'
;

export const ARCHITECTURE_TEXTURE_KEYS = [
  'floor_wood_planks_dark',
  'floor_herringbone_dark',
  'floor_marble_black_veined',
  'floor_stone_blocks_dark',
  'floor_wood_inlay_ornate',
  'floor_marble_border_corner_a',
  'floor_marble_border_corner_b',
  'floor_threshold_gold',
  'floor_wood_planks_alt',
  'floor_stone_cracked',
  'floor_stone_polished_reflective',
  'carpet_crimson_border',
  'carpet_crimson_corner',
  'floor_black_gold_grid',
  'floor_medallion_octagonal',
  'wall_panel_wood_horizontal',
  'wall_panel_damask_crimson',
  'wall_panel_stone_masonry',
  'wall_panel_wood_wainscot_a',
  'wall_panel_fleur_ornate',
  'wall_panel_stone_framed_gold',
  'wall_panel_wood_wainscot_b',
  'wall_panel_fleur_small',
  'wall_panel_wood_framed_plain',
  'wall_panel_stone_framed_light',
  'wall_panel_stone_cracked',
  'wall_niche_bust',
  'trim_cornice_wood_a',
  'trim_cornice_wood_b',
  'trim_cornice_studded',
  'trim_moulding_horizontal',
  'trim_corner_inside',
  'trim_corner_outside',
  'trim_vertical_strip_a',
  'trim_vertical_strip_b',
  'trim_corbel_curved',
  'column_wood_fluted',
  'column_wood_corinthian',
  'column_wood_gold_trim',
  'column_stone_fluted',
  'column_stone_massive',
  'column_stone_slender',
  'column_wood_capital_ornate',
  'column_wood_ringed',
  'arch_gothic_pointed_stone',
  'arch_gothic_pointed_gold',
  'corbel_shield_fleur',
  'arch_spandrel_left',
  'arch_spandrel_right',
  'half_column_wood_gold',
  'half_column_stone_gold',
  'corbel_ornate_foliage',
  'wall_niche_empty',
  'balustrade_section',
  'balustrade_post',
  'newel_post_large',
  'newel_post_small',
  'stair_stringer_step_left',
  'stair_stringer_step_right',
  'stair_stringer_bottom_left',
  'stair_tread_wide',
  'stair_tread_medium',
  'stair_runner_carpet_wide',
  'stair_runner_carpet_left_edge',
  'stair_runner_carpet_right_edge',
  'stair_rod_brass',
  'stair_rod_finial_left',
  'stair_rod_finial_right',
  'ornament_fleur_de_lis',
  'ornament_foliage_crest_a',
  'ornament_foliage_crest_b',
  'ornament_rosette_round',
  'trim_moulding_ribbed_h',
  'trim_moulding_ribbed_v',
  'ornament_boss_square',
  'trim_gold_pattern_x',
  'panel_inset_stone_pale',
  'panel_inset_wood_gold',
  'ornament_medallion_rosette_large',
  'panel_cross_gold',
] as const;

export type ArchitectureTextureKey = (typeof ARCHITECTURE_TEXTURE_KEYS)[number];

export const CATEGORY_MAP: Record<ArchitectureTextureKey, ArchitectureCategory> = {
  floor_wood_planks_dark: 'floors',
  floor_herringbone_dark: 'floors',
  floor_marble_black_veined: 'floors',
  floor_stone_blocks_dark: 'floors',
  floor_wood_inlay_ornate: 'floors',
  floor_marble_border_corner_a: 'floors',
  floor_marble_border_corner_b: 'floors',
  floor_threshold_gold: 'floors',
  floor_wood_planks_alt: 'floors',
  floor_stone_cracked: 'floors',
  floor_stone_polished_reflective: 'floors',
  carpet_crimson_border: 'carpets',
  carpet_crimson_corner: 'carpets',
  floor_black_gold_grid: 'floors',
  floor_medallion_octagonal: 'floors',
  wall_panel_wood_horizontal: 'walls',
  wall_panel_damask_crimson: 'walls',
  wall_panel_stone_masonry: 'walls',
  wall_panel_wood_wainscot_a: 'walls',
  wall_panel_fleur_ornate: 'walls',
  wall_panel_stone_framed_gold: 'walls',
  wall_panel_wood_wainscot_b: 'walls',
  wall_panel_fleur_small: 'walls',
  wall_panel_wood_framed_plain: 'walls',
  wall_panel_stone_framed_light: 'walls',
  wall_panel_stone_cracked: 'walls',
  wall_niche_bust: 'walls',
  trim_cornice_wood_a: 'trims',
  trim_cornice_wood_b: 'trims',
  trim_cornice_studded: 'trims',
  trim_moulding_horizontal: 'trims',
  trim_corner_inside: 'trims',
  trim_corner_outside: 'trims',
  trim_vertical_strip_a: 'trims',
  trim_vertical_strip_b: 'trims',
  trim_corbel_curved: 'trims',
  column_wood_fluted: 'columns_arches',
  column_wood_corinthian: 'columns_arches',
  column_wood_gold_trim: 'columns_arches',
  column_stone_fluted: 'columns_arches',
  column_stone_massive: 'columns_arches',
  column_stone_slender: 'columns_arches',
  column_wood_capital_ornate: 'columns_arches',
  column_wood_ringed: 'columns_arches',
  arch_gothic_pointed_stone: 'columns_arches',
  arch_gothic_pointed_gold: 'columns_arches',
  corbel_shield_fleur: 'columns_arches',
  arch_spandrel_left: 'columns_arches',
  arch_spandrel_right: 'columns_arches',
  half_column_wood_gold: 'columns_arches',
  half_column_stone_gold: 'columns_arches',
  corbel_ornate_foliage: 'columns_arches',
  wall_niche_empty: 'columns_arches',
  balustrade_section: 'stairs_balustrade',
  balustrade_post: 'stairs_balustrade',
  newel_post_large: 'stairs_balustrade',
  newel_post_small: 'stairs_balustrade',
  stair_stringer_step_left: 'stairs_balustrade',
  stair_stringer_step_right: 'stairs_balustrade',
  stair_stringer_bottom_left: 'stairs_balustrade',
  stair_tread_wide: 'stairs_balustrade',
  stair_tread_medium: 'stairs_balustrade',
  stair_runner_carpet_wide: 'stairs_balustrade',
  stair_runner_carpet_left_edge: 'stairs_balustrade',
  stair_runner_carpet_right_edge: 'stairs_balustrade',
  stair_rod_brass: 'stairs_balustrade',
  stair_rod_finial_left: 'stairs_balustrade',
  stair_rod_finial_right: 'stairs_balustrade',
  ornament_fleur_de_lis: 'ornaments',
  ornament_foliage_crest_a: 'ornaments',
  ornament_foliage_crest_b: 'ornaments',
  ornament_rosette_round: 'ornaments',
  trim_moulding_ribbed_h: 'ornaments',
  trim_moulding_ribbed_v: 'ornaments',
  ornament_boss_square: 'ornaments',
  trim_gold_pattern_x: 'ornaments',
  panel_inset_stone_pale: 'ornaments',
  panel_inset_wood_gold: 'ornaments',
  ornament_medallion_rosette_large: 'ornaments',
  panel_cross_gold: 'ornaments',
};

export function getArchitectureAssetPath(key: ArchitectureTextureKey): string {
  const category = CATEGORY_MAP[key];
  return `game-assets/environment/mansion/architecture/${category}/${key}.png`;
}

export function preloadMansionArchitecture(scene: Phaser.Scene): void {
  for (const key of ARCHITECTURE_TEXTURE_KEYS) {
    if (!scene.textures.exists(key)) {
      scene.load.image(key, getArchitectureAssetPath(key));
    }
  }
}
