import { EnvironmentAssetDef } from './EnvironmentAsset';
import { CollisionProfile, getCollisionProfile } from './CollisionProfile';

export const ENVIRONMENT_ASSETS: Record<string, EnvironmentAssetDef> = {
  'floor_wood_planks_dark': {
    "id": "floor_wood_planks_dark",
    "category": "floors",
    "textureKey": "floor_wood_planks_dark",
    "nativeWidth": 98,
    "nativeHeight": 98,
    "anchorPreset": "top-left",
    "depthClass": "floor",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Dark mahogany plank flooring"
},
  'floor_herringbone_dark': {
    "id": "floor_herringbone_dark",
    "category": "floors",
    "textureKey": "floor_herringbone_dark",
    "nativeWidth": 98,
    "nativeHeight": 98,
    "anchorPreset": "top-left",
    "depthClass": "floor",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Herringbone / parquet dark wood floor"
},
  'floor_marble_black_veined': {
    "id": "floor_marble_black_veined",
    "category": "floors",
    "textureKey": "floor_marble_black_veined",
    "nativeWidth": 98,
    "nativeHeight": 98,
    "anchorPreset": "top-left",
    "depthClass": "floor",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Black veined polished marble"
},
  'floor_stone_blocks_dark': {
    "id": "floor_stone_blocks_dark",
    "category": "floors",
    "textureKey": "floor_stone_blocks_dark",
    "nativeWidth": 99,
    "nativeHeight": 99,
    "anchorPreset": "top-left",
    "depthClass": "floor",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Dark slate stone block tile"
},
  'floor_wood_inlay_ornate': {
    "id": "floor_wood_inlay_ornate",
    "category": "floors",
    "textureKey": "floor_wood_inlay_ornate",
    "nativeWidth": 99,
    "nativeHeight": 101,
    "anchorPreset": "top-left",
    "depthClass": "floor",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Ornate wood inset diamond floor tile"
},
  'floor_marble_border_corner_a': {
    "id": "floor_marble_border_corner_a",
    "category": "floors",
    "textureKey": "floor_marble_border_corner_a",
    "nativeWidth": 100,
    "nativeHeight": 102,
    "anchorPreset": "top-left",
    "depthClass": "floor",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Pale marble corner border with dark stone inset"
},
  'floor_marble_border_corner_b': {
    "id": "floor_marble_border_corner_b",
    "category": "floors",
    "textureKey": "floor_marble_border_corner_b",
    "nativeWidth": 113,
    "nativeHeight": 101,
    "anchorPreset": "top-left",
    "depthClass": "floor",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Pale marble corner border with dark veined marble"
},
  'floor_threshold_gold': {
    "id": "floor_threshold_gold",
    "category": "floors",
    "textureKey": "floor_threshold_gold",
    "nativeWidth": 103,
    "nativeHeight": 99,
    "anchorPreset": "top-left",
    "depthClass": "floor",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Dark wood floor module with antique gold threshold trim"
},
  'floor_wood_planks_alt': {
    "id": "floor_wood_planks_alt",
    "category": "floors",
    "textureKey": "floor_wood_planks_alt",
    "nativeWidth": 99,
    "nativeHeight": 105,
    "anchorPreset": "top-left",
    "depthClass": "floor",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Alternate dark wood plank tile"
},
  'floor_stone_cracked': {
    "id": "floor_stone_cracked",
    "category": "floors",
    "textureKey": "floor_stone_cracked",
    "nativeWidth": 98,
    "nativeHeight": 105,
    "anchorPreset": "top-left",
    "depthClass": "floor",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Aged cracked dark stone floor tile"
},
  'floor_stone_polished_reflective': {
    "id": "floor_stone_polished_reflective",
    "category": "floors",
    "textureKey": "floor_stone_polished_reflective",
    "nativeWidth": 100,
    "nativeHeight": 106,
    "anchorPreset": "top-left",
    "depthClass": "floor",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Polished reflective stone tile with vertical specular streak"
},
  'carpet_crimson_border': {
    "id": "carpet_crimson_border",
    "category": "carpets",
    "textureKey": "carpet_crimson_border",
    "nativeWidth": 109,
    "nativeHeight": 107,
    "anchorPreset": "top-left",
    "depthClass": "floor-decor",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Crimson velvet carpet with embroidered gold border"
},
  'carpet_crimson_corner': {
    "id": "carpet_crimson_corner",
    "category": "carpets",
    "textureKey": "carpet_crimson_corner",
    "nativeWidth": 107,
    "nativeHeight": 108,
    "anchorPreset": "top-left",
    "depthClass": "floor-decor",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Crimson velvet carpet corner with embroidered gold border"
},
  'floor_black_gold_grid': {
    "id": "floor_black_gold_grid",
    "category": "floors",
    "textureKey": "floor_black_gold_grid",
    "nativeWidth": 104,
    "nativeHeight": 108,
    "anchorPreset": "top-left",
    "depthClass": "floor",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Black square floor tile with gold diamond intersections"
},
  'floor_medallion_octagonal': {
    "id": "floor_medallion_octagonal",
    "category": "floors",
    "textureKey": "floor_medallion_octagonal",
    "nativeWidth": 111,
    "nativeHeight": 111,
    "anchorPreset": "top-left",
    "depthClass": "floor",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Large octagonal ornamental compass medallion in gold frame"
},
  'wall_panel_wood_horizontal': {
    "id": "wall_panel_wood_horizontal",
    "category": "walls",
    "textureKey": "wall_panel_wood_horizontal",
    "nativeWidth": 100,
    "nativeHeight": 150,
    "anchorPreset": "top-left",
    "depthClass": "back-wall",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Dark horizontal wood plank wall panel with moulded base and cap"
},
  'wall_panel_damask_crimson': {
    "id": "wall_panel_damask_crimson",
    "category": "walls",
    "textureKey": "wall_panel_damask_crimson",
    "nativeWidth": 96,
    "nativeHeight": 151,
    "anchorPreset": "top-left",
    "depthClass": "back-wall",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Rich crimson damask fabric wall panel in dark wood frame"
},
  'wall_panel_stone_masonry': {
    "id": "wall_panel_stone_masonry",
    "category": "walls",
    "textureKey": "wall_panel_stone_masonry",
    "nativeWidth": 92,
    "nativeHeight": 150,
    "anchorPreset": "top-left",
    "depthClass": "back-wall",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Dark ashlar masonry stone block panel"
},
  'wall_panel_wood_wainscot_a': {
    "id": "wall_panel_wood_wainscot_a",
    "category": "walls",
    "textureKey": "wall_panel_wood_wainscot_a",
    "nativeWidth": 97,
    "nativeHeight": 150,
    "anchorPreset": "top-left",
    "depthClass": "back-wall",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Dark wood vertical panel with coffered wainscot base"
},
  'wall_panel_fleur_ornate': {
    "id": "wall_panel_fleur_ornate",
    "category": "walls",
    "textureKey": "wall_panel_fleur_ornate",
    "nativeWidth": 97,
    "nativeHeight": 150,
    "anchorPreset": "top-left",
    "depthClass": "back-wall",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Ornate dark wood panel with carved gold fleur-de-lis and beaded inner frame"
},
  'wall_panel_stone_framed_gold': {
    "id": "wall_panel_stone_framed_gold",
    "category": "walls",
    "textureKey": "wall_panel_stone_framed_gold",
    "nativeWidth": 95,
    "nativeHeight": 146,
    "anchorPreset": "top-left",
    "depthClass": "back-wall",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Grey stone panel with gold inner filigree frame"
},
  'wall_panel_wood_wainscot_b': {
    "id": "wall_panel_wood_wainscot_b",
    "category": "walls",
    "textureKey": "wall_panel_wood_wainscot_b",
    "nativeWidth": 97,
    "nativeHeight": 149,
    "anchorPreset": "top-left",
    "depthClass": "back-wall",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Dark wood panel variant with coffered wainscot base"
},
  'wall_panel_fleur_small': {
    "id": "wall_panel_fleur_small",
    "category": "walls",
    "textureKey": "wall_panel_fleur_small",
    "nativeWidth": 92,
    "nativeHeight": 140,
    "anchorPreset": "top-left",
    "depthClass": "back-wall",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Dark wood panel with gold fleur-de-lis emblem"
},
  'wall_panel_wood_framed_plain': {
    "id": "wall_panel_wood_framed_plain",
    "category": "walls",
    "textureKey": "wall_panel_wood_framed_plain",
    "nativeWidth": 95,
    "nativeHeight": 147,
    "anchorPreset": "top-left",
    "depthClass": "back-wall",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Classic dark wood framed wall panel"
},
  'wall_panel_stone_framed_light': {
    "id": "wall_panel_stone_framed_light",
    "category": "walls",
    "textureKey": "wall_panel_stone_framed_light",
    "nativeWidth": 93,
    "nativeHeight": 146,
    "anchorPreset": "top-left",
    "depthClass": "back-wall",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Pale carved stone framed wall panel"
},
  'wall_panel_stone_cracked': {
    "id": "wall_panel_stone_cracked",
    "category": "walls",
    "textureKey": "wall_panel_stone_cracked",
    "nativeWidth": 88,
    "nativeHeight": 146,
    "anchorPreset": "top-left",
    "depthClass": "back-wall",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Cracked ancient stone wall panel with brass base trim"
},
  'wall_niche_bust': {
    "id": "wall_niche_bust",
    "category": "walls",
    "textureKey": "wall_niche_bust",
    "nativeWidth": 92,
    "nativeHeight": 146,
    "anchorPreset": "bottom-center",
    "depthClass": "back-wall-detail",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Gothic pointed arch stone niche housing a classical sculptural bust"
},
  'trim_cornice_wood_a': {
    "id": "trim_cornice_wood_a",
    "category": "trims",
    "textureKey": "trim_cornice_wood_a",
    "nativeWidth": 183,
    "nativeHeight": 49,
    "anchorPreset": "bottom-center",
    "depthClass": "back-wall-detail",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Heavy dark wood architectural cornice / baseboard moulding"
},
  'trim_cornice_wood_b': {
    "id": "trim_cornice_wood_b",
    "category": "trims",
    "textureKey": "trim_cornice_wood_b",
    "nativeWidth": 159,
    "nativeHeight": 47,
    "anchorPreset": "bottom-center",
    "depthClass": "back-wall-detail",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Medium dark wood architectural cornice"
},
  'trim_cornice_studded': {
    "id": "trim_cornice_studded",
    "category": "trims",
    "textureKey": "trim_cornice_studded",
    "nativeWidth": 176,
    "nativeHeight": 50,
    "anchorPreset": "bottom-center",
    "depthClass": "back-wall-detail",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Architectural wood cornice with decorative gold studded dentil frieze"
},
  'trim_moulding_horizontal': {
    "id": "trim_moulding_horizontal",
    "category": "trims",
    "textureKey": "trim_moulding_horizontal",
    "nativeWidth": 210,
    "nativeHeight": 36,
    "anchorPreset": "bottom-center",
    "depthClass": "back-wall-detail",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Long slender horizontal wood dado rail / trim moulding"
},
  'trim_corner_inside': {
    "id": "trim_corner_inside",
    "category": "trims",
    "textureKey": "trim_corner_inside",
    "nativeWidth": 91,
    "nativeHeight": 95,
    "anchorPreset": "top-left",
    "depthClass": "back-wall-detail",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Internal corner junction piece with tiered moulding"
},
  'trim_corner_outside': {
    "id": "trim_corner_outside",
    "category": "trims",
    "textureKey": "trim_corner_outside",
    "nativeWidth": 57,
    "nativeHeight": 101,
    "anchorPreset": "top-left",
    "depthClass": "back-wall-detail",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "External corner / architectural pillar plinth with gold rim"
},
  'trim_vertical_strip_a': {
    "id": "trim_vertical_strip_a",
    "category": "trims",
    "textureKey": "trim_vertical_strip_a",
    "nativeWidth": 48,
    "nativeHeight": 97,
    "anchorPreset": "top-left",
    "depthClass": "back-wall-detail",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Vertical panel divider strip with stepped gold highlight"
},
  'trim_vertical_strip_b': {
    "id": "trim_vertical_strip_b",
    "category": "trims",
    "textureKey": "trim_vertical_strip_b",
    "nativeWidth": 46,
    "nativeHeight": 97,
    "anchorPreset": "top-left",
    "depthClass": "back-wall-detail",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Vertical panel divider strip variant"
},
  'trim_corbel_curved': {
    "id": "trim_corbel_curved",
    "category": "trims",
    "textureKey": "trim_corbel_curved",
    "nativeWidth": 76,
    "nativeHeight": 92,
    "anchorPreset": "bottom-center",
    "depthClass": "back-wall-detail",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Carved architectural bracket / curved corner corbel"
},
  'column_wood_fluted': {
    "id": "column_wood_fluted",
    "category": "columns_arches",
    "textureKey": "column_wood_fluted",
    "nativeWidth": 45,
    "nativeHeight": 160,
    "anchorPreset": "bottom-center",
    "depthClass": "dynamic-solid",
    "physicalClass": "floor-solid",
    "collisionProfile": "column_fluted",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Dark fluted wood column with base plinth and carved capital"
},
  'column_wood_corinthian': {
    "id": "column_wood_corinthian",
    "category": "columns_arches",
    "textureKey": "column_wood_corinthian",
    "nativeWidth": 64,
    "nativeHeight": 161,
    "anchorPreset": "bottom-center",
    "depthClass": "dynamic-solid",
    "physicalClass": "floor-solid",
    "collisionProfile": "column_wood",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Wood column with broad ornate Corinthian acanthus capital"
},
  'column_wood_gold_trim': {
    "id": "column_wood_gold_trim",
    "category": "columns_arches",
    "textureKey": "column_wood_gold_trim",
    "nativeWidth": 49,
    "nativeHeight": 162,
    "anchorPreset": "bottom-center",
    "depthClass": "dynamic-solid",
    "physicalClass": "floor-solid",
    "collisionProfile": "column_wood",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Dark wood fluted column with gold brass collar rings"
},
  'column_stone_fluted': {
    "id": "column_stone_fluted",
    "category": "columns_arches",
    "textureKey": "column_stone_fluted",
    "nativeWidth": 49,
    "nativeHeight": 163,
    "anchorPreset": "bottom-center",
    "depthClass": "dynamic-solid",
    "physicalClass": "floor-solid",
    "collisionProfile": "column_fluted",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Grey fluted stone column with gold collar rings"
},
  'column_stone_massive': {
    "id": "column_stone_massive",
    "category": "columns_arches",
    "textureKey": "column_stone_massive",
    "nativeWidth": 73,
    "nativeHeight": 160,
    "anchorPreset": "bottom-center",
    "depthClass": "dynamic-solid",
    "physicalClass": "floor-solid",
    "collisionProfile": "column_massive",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Massive grey stone column with wide base and ornate gold filigree capital"
},
  'column_stone_slender': {
    "id": "column_stone_slender",
    "category": "columns_arches",
    "textureKey": "column_stone_slender",
    "nativeWidth": 38,
    "nativeHeight": 159,
    "anchorPreset": "bottom-center",
    "depthClass": "dynamic-solid",
    "physicalClass": "floor-solid",
    "collisionProfile": "column_wood",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Slender grey stone pillar with brass rings"
},
  'column_wood_capital_ornate': {
    "id": "column_wood_capital_ornate",
    "category": "columns_arches",
    "textureKey": "column_wood_capital_ornate",
    "nativeWidth": 70,
    "nativeHeight": 159,
    "anchorPreset": "bottom-center",
    "depthClass": "dynamic-solid",
    "physicalClass": "floor-solid",
    "collisionProfile": "column_wood",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Dark wood column with elaborate sculpted gold capital"
},
  'column_wood_ringed': {
    "id": "column_wood_ringed",
    "category": "columns_arches",
    "textureKey": "column_wood_ringed",
    "nativeWidth": 49,
    "nativeHeight": 157,
    "anchorPreset": "bottom-center",
    "depthClass": "dynamic-solid",
    "physicalClass": "floor-solid",
    "collisionProfile": "column_wood",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Medium dark wood column with brass astragal rings"
},
  'arch_gothic_pointed_stone': {
    "id": "arch_gothic_pointed_stone",
    "category": "columns_arches",
    "textureKey": "arch_gothic_pointed_stone",
    "nativeWidth": 136,
    "nativeHeight": 154,
    "anchorPreset": "bottom-center",
    "depthClass": "back-wall-detail",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Pointed gothic arch in grey stone with gold fleur finial"
},
  'arch_gothic_pointed_gold': {
    "id": "arch_gothic_pointed_gold",
    "category": "columns_arches",
    "textureKey": "arch_gothic_pointed_gold",
    "nativeWidth": 137,
    "nativeHeight": 160,
    "anchorPreset": "bottom-center",
    "depthClass": "back-wall-detail",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Elaborate pointed gothic arch in dark wood and gold filigree"
},
  'corbel_shield_fleur': {
    "id": "corbel_shield_fleur",
    "category": "columns_arches",
    "textureKey": "corbel_shield_fleur",
    "nativeWidth": 62,
    "nativeHeight": 92,
    "anchorPreset": "center",
    "depthClass": "back-wall-detail",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Triangular stone wall bracket / corbel pendant with gold fleur-de-lis"
},
  'arch_spandrel_left': {
    "id": "arch_spandrel_left",
    "category": "columns_arches",
    "textureKey": "arch_spandrel_left",
    "nativeWidth": 77,
    "nativeHeight": 101,
    "anchorPreset": "center",
    "depthClass": "back-wall-detail",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Left arch spandrel bracket with gold rosette and filigree border"
},
  'arch_spandrel_right': {
    "id": "arch_spandrel_right",
    "category": "columns_arches",
    "textureKey": "arch_spandrel_right",
    "nativeWidth": 78,
    "nativeHeight": 101,
    "anchorPreset": "center",
    "depthClass": "back-wall-detail",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Right arch spandrel bracket with gold rosette and filigree border"
},
  'half_column_wood_gold': {
    "id": "half_column_wood_gold",
    "category": "columns_arches",
    "textureKey": "half_column_wood_gold",
    "nativeWidth": 43,
    "nativeHeight": 144,
    "anchorPreset": "bottom-center",
    "depthClass": "dynamic-solid",
    "physicalClass": "floor-solid",
    "collisionProfile": "half_column",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Engaged half-column in dark wood with gold vertical fluting"
},
  'half_column_stone_gold': {
    "id": "half_column_stone_gold",
    "category": "columns_arches",
    "textureKey": "half_column_stone_gold",
    "nativeWidth": 36,
    "nativeHeight": 144,
    "anchorPreset": "bottom-center",
    "depthClass": "dynamic-solid",
    "physicalClass": "floor-solid",
    "collisionProfile": "half_column",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Engaged half-column in grey stone with gold collar rings"
},
  'corbel_ornate_foliage': {
    "id": "corbel_ornate_foliage",
    "category": "columns_arches",
    "textureKey": "corbel_ornate_foliage",
    "nativeWidth": 66,
    "nativeHeight": 136,
    "anchorPreset": "center",
    "depthClass": "back-wall-detail",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Carved architectural wall corbel with classical volutes and acanthus leaves"
},
  'wall_niche_empty': {
    "id": "wall_niche_empty",
    "category": "columns_arches",
    "textureKey": "wall_niche_empty",
    "nativeWidth": 62,
    "nativeHeight": 167,
    "anchorPreset": "center",
    "depthClass": "back-wall-detail",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Tall pointed gothic wall niche / recess in dark stone"
},
  'balustrade_section': {
    "id": "balustrade_section",
    "category": "stairs_balustrade",
    "textureKey": "balustrade_section",
    "nativeWidth": 132,
    "nativeHeight": 115,
    "anchorPreset": "bottom-center",
    "depthClass": "dynamic-solid",
    "physicalClass": "barrier",
    "collisionProfile": "balustrade_horizontal_132",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Full carved dark wood balustrade railing section with 4 turned balusters"
},
  'balustrade_post': {
    "id": "balustrade_post",
    "category": "stairs_balustrade",
    "textureKey": "balustrade_post",
    "nativeWidth": 34,
    "nativeHeight": 136,
    "anchorPreset": "bottom-center",
    "depthClass": "dynamic-solid",
    "physicalClass": "floor-solid",
    "collisionProfile": "newel_small",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Individual turned wooden baluster / support spindle"
},
  'newel_post_large': {
    "id": "newel_post_large",
    "category": "stairs_balustrade",
    "textureKey": "newel_post_large",
    "nativeWidth": 42,
    "nativeHeight": 128,
    "anchorPreset": "bottom-center",
    "depthClass": "dynamic-solid",
    "physicalClass": "floor-solid",
    "collisionProfile": "newel_large",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Substantial staircase newel post with spherical brass finial"
},
  'newel_post_small': {
    "id": "newel_post_small",
    "category": "stairs_balustrade",
    "textureKey": "newel_post_small",
    "nativeWidth": 40,
    "nativeHeight": 101,
    "anchorPreset": "bottom-center",
    "depthClass": "dynamic-solid",
    "physicalClass": "floor-solid",
    "collisionProfile": "newel_small",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Medium staircase newel post with spherical brass finial"
},
  'stair_stringer_step_left': {
    "id": "stair_stringer_step_left",
    "category": "stairs_balustrade",
    "textureKey": "stair_stringer_step_left",
    "nativeWidth": 57,
    "nativeHeight": 125,
    "anchorPreset": "bottom-center",
    "depthClass": "dynamic-solid",
    "physicalClass": "barrier",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Staircase left side stringer / skirting transition block with gold cross"
},
  'stair_stringer_step_right': {
    "id": "stair_stringer_step_right",
    "category": "stairs_balustrade",
    "textureKey": "stair_stringer_step_right",
    "nativeWidth": 58,
    "nativeHeight": 122,
    "anchorPreset": "bottom-center",
    "depthClass": "dynamic-solid",
    "physicalClass": "barrier",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Staircase right side stringer / skirting transition block with gold cross"
},
  'stair_stringer_bottom_left': {
    "id": "stair_stringer_bottom_left",
    "category": "stairs_balustrade",
    "textureKey": "stair_stringer_bottom_left",
    "nativeWidth": 87,
    "nativeHeight": 122,
    "anchorPreset": "bottom-center",
    "depthClass": "dynamic-solid",
    "physicalClass": "barrier",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Staircase bottom landing stepped plinth stringer with gold cross"
},
  'stair_tread_wide': {
    "id": "stair_tread_wide",
    "category": "stairs_balustrade",
    "textureKey": "stair_tread_wide",
    "nativeWidth": 97,
    "nativeHeight": 70,
    "anchorPreset": "center",
    "depthClass": "floor",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Dark mahogany wood stair step tread (top perspective)"
},
  'stair_tread_medium': {
    "id": "stair_tread_medium",
    "category": "stairs_balustrade",
    "textureKey": "stair_tread_medium",
    "nativeWidth": 100,
    "nativeHeight": 66,
    "anchorPreset": "center",
    "depthClass": "floor",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Dark mahogany wood stair step tread variant"
},
  'stair_runner_carpet_wide': {
    "id": "stair_runner_carpet_wide",
    "category": "stairs_balustrade",
    "textureKey": "stair_runner_carpet_wide",
    "nativeWidth": 123,
    "nativeHeight": 76,
    "anchorPreset": "center",
    "depthClass": "floor",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Crimson stair-runner carpet section with gold embroidered borders"
},
  'stair_runner_carpet_left_edge': {
    "id": "stair_runner_carpet_left_edge",
    "category": "stairs_balustrade",
    "textureKey": "stair_runner_carpet_left_edge",
    "nativeWidth": 63,
    "nativeHeight": 75,
    "anchorPreset": "center",
    "depthClass": "floor",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Crimson stair-runner left border segment"
},
  'stair_runner_carpet_right_edge': {
    "id": "stair_runner_carpet_right_edge",
    "category": "stairs_balustrade",
    "textureKey": "stair_runner_carpet_right_edge",
    "nativeWidth": 59,
    "nativeHeight": 76,
    "anchorPreset": "center",
    "depthClass": "floor",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Crimson stair-runner right border segment"
},
  'stair_rod_brass': {
    "id": "stair_rod_brass",
    "category": "stairs_balustrade",
    "textureKey": "stair_rod_brass",
    "nativeWidth": 155,
    "nativeHeight": 29,
    "anchorPreset": "center",
    "depthClass": "floor",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Polished brass stair carpet rod with spherical end finials"
},
  'stair_rod_finial_left': {
    "id": "stair_rod_finial_left",
    "category": "stairs_balustrade",
    "textureKey": "stair_rod_finial_left",
    "nativeWidth": 34,
    "nativeHeight": 27,
    "anchorPreset": "center",
    "depthClass": "floor",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Brass stair rod end bracket"
},
  'stair_rod_finial_right': {
    "id": "stair_rod_finial_right",
    "category": "stairs_balustrade",
    "textureKey": "stair_rod_finial_right",
    "nativeWidth": 25,
    "nativeHeight": 26,
    "anchorPreset": "center",
    "depthClass": "floor",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Brass spherical finial cap"
},
  'ornament_fleur_de_lis': {
    "id": "ornament_fleur_de_lis",
    "category": "ornaments",
    "textureKey": "ornament_fleur_de_lis",
    "nativeWidth": 66,
    "nativeHeight": 87,
    "anchorPreset": "center",
    "depthClass": "back-wall-detail",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Carved gold fleur-de-lis wall ornament"
},
  'ornament_foliage_crest_a': {
    "id": "ornament_foliage_crest_a",
    "category": "ornaments",
    "textureKey": "ornament_foliage_crest_a",
    "nativeWidth": 109,
    "nativeHeight": 116,
    "anchorPreset": "center",
    "depthClass": "back-wall-detail",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Carved gold acanthus foliage pediment crest"
},
  'ornament_foliage_crest_b': {
    "id": "ornament_foliage_crest_b",
    "category": "ornaments",
    "textureKey": "ornament_foliage_crest_b",
    "nativeWidth": 110,
    "nativeHeight": 116,
    "anchorPreset": "center",
    "depthClass": "back-wall-detail",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Carved gold scroll foliage wall ornament"
},
  'ornament_rosette_round': {
    "id": "ornament_rosette_round",
    "category": "ornaments",
    "textureKey": "ornament_rosette_round",
    "nativeWidth": 75,
    "nativeHeight": 78,
    "anchorPreset": "center",
    "depthClass": "back-wall-detail",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Circular carved gold flower rosette"
},
  'trim_moulding_ribbed_h': {
    "id": "trim_moulding_ribbed_h",
    "category": "ornaments",
    "textureKey": "trim_moulding_ribbed_h",
    "nativeWidth": 106,
    "nativeHeight": 39,
    "anchorPreset": "center",
    "depthClass": "back-wall-detail",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Horizontal ribbed wood moulding with gold inlay"
},
  'trim_moulding_ribbed_v': {
    "id": "trim_moulding_ribbed_v",
    "category": "ornaments",
    "textureKey": "trim_moulding_ribbed_v",
    "nativeWidth": 36,
    "nativeHeight": 84,
    "anchorPreset": "center",
    "depthClass": "back-wall-detail",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Vertical ribbed wood moulding with gold inlay"
},
  'ornament_boss_square': {
    "id": "ornament_boss_square",
    "category": "ornaments",
    "textureKey": "ornament_boss_square",
    "nativeWidth": 74,
    "nativeHeight": 68,
    "anchorPreset": "center",
    "depthClass": "back-wall-detail",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Pyramidal square boss with gold frame"
},
  'trim_gold_pattern_x': {
    "id": "trim_gold_pattern_x",
    "category": "ornaments",
    "textureKey": "trim_gold_pattern_x",
    "nativeWidth": 202,
    "nativeHeight": 36,
    "anchorPreset": "center",
    "depthClass": "back-wall-detail",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": true,
    "notes": "Long horizontal dark wood trim with gold criss-cross pattern"
},
  'panel_inset_stone_pale': {
    "id": "panel_inset_stone_pale",
    "category": "ornaments",
    "textureKey": "panel_inset_stone_pale",
    "nativeWidth": 97,
    "nativeHeight": 113,
    "anchorPreset": "center",
    "depthClass": "back-wall-detail",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Pale carved stone wall inset with stepped frame"
},
  'panel_inset_wood_gold': {
    "id": "panel_inset_wood_gold",
    "category": "ornaments",
    "textureKey": "panel_inset_wood_gold",
    "nativeWidth": 96,
    "nativeHeight": 117,
    "anchorPreset": "center",
    "depthClass": "back-wall-detail",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Dark wood framed wall inset with gold corner flourishes"
},
  'ornament_medallion_rosette_large': {
    "id": "ornament_medallion_rosette_large",
    "category": "ornaments",
    "textureKey": "ornament_medallion_rosette_large",
    "nativeWidth": 107,
    "nativeHeight": 112,
    "anchorPreset": "center",
    "depthClass": "back-wall-detail",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Large circular medallion with intricate foliage rosette"
},
  'panel_cross_gold': {
    "id": "panel_cross_gold",
    "category": "ornaments",
    "textureKey": "panel_cross_gold",
    "nativeWidth": 94,
    "nativeHeight": 115,
    "anchorPreset": "center",
    "depthClass": "back-wall-detail",
    "physicalClass": "none",
    "collisionProfile": "none",
    "mirrorSafe": true,
    "repeatable": false,
    "notes": "Dark wood panel with prominent gold filigree cross"
},
};

export class EnvironmentAssetCatalog {
  private static assets: Map<string, EnvironmentAssetDef> = new Map(
    Object.entries(ENVIRONMENT_ASSETS)
  );

  public static registerAsset(def: EnvironmentAssetDef): void {
    this.assets.set(def.id, def);
  }

  public static getAsset(id: string): EnvironmentAssetDef | undefined {
    return this.assets.get(id);
  }

  public static requireAsset(id: string): EnvironmentAssetDef {
    const asset = this.assets.get(id);
    if (!asset) {
      throw new Error(`Environment asset not found in catalog: ${id}`);
    }
    return asset;
  }

  public static hasAsset(id: string): boolean {
    return this.assets.has(id);
  }

  public static getAllAssets(): EnvironmentAssetDef[] {
    return Array.from(this.assets.values());
  }

  public static getAssetsByCategory(category: string): EnvironmentAssetDef[] {
    return this.getAllAssets().filter((a) => a.category === category);
  }

  public static getCollisionProfileForAsset(id: string): CollisionProfile {
    const asset = this.assets.get(id);
    if (!asset) return getCollisionProfile('none');
    return getCollisionProfile(asset.collisionProfile);
  }
}
